server:
  port: 8081
spring:
  application:
    name: hmdp
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${power.mysql.ip}:${power.mysql.port}/${power.mysql.db}?useSSL=false&serverTimezone=UTC
    username: ${power.mysql.username}
    password: ${power.mysql.password}
  redis:
    host: ${power.redis.ip}
    port: ${power.redis.port}
    password: ${power.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug